var data = {"users":[
  {
  "firstName":"Ben",
  "lastName":"John",
  "userName":"Benstar",
  "password":"admin",
  "overallScore":""
  },
  {
  "firstName":"Christoph",
  "lastName":"Ueberle",
  "userName":"Crystal",
  "password":"admin",
  "overallScore":""
  },
  {
  "firstName":"Berfin",
  "lastName":"Özgun",
  "userName":"Befee",
  "password":"ChristophIstToll",
  "overallScore":""
  }
]}
