var data = {"users":[
  {
  "firstName":"John",
  "lastName":"Doe",
  "userName":"NachtBärchi007",
  "password":"admin",
  "overallScore":""
  },
  {
  "firstName":"Jane",
  "lastName":"Doe",
  "userName":"Nacht007",
  "password":"admirana",
  "overallScore":""
  },
  {
  "firstName":"Jane",
  "lastName":"Doe",
  "userName":"Day007",
  "password":"admiranas",
  "overallScore":""
  },
  {
  "firstName":"Jane",
  "lastName":"Doe",
  "userName":"Nacht009",
  "password":"admir",
  "overallScore":""
  }

]}
